export const GET_ORDERS_DATA="GET_ORDERS_DATA"
export const GET_ORDERS_DETAILS_DATA="GET_ORDERS_DETAILS_DATA"
export const ORDERS_DETAILS_RES_DATA="ORDERS_DETAILS_RES_DATA"
export const ORDERS_CANCEL_RES_DATA="ORDERS_CANCEL_RES_DATA"
export const ORDERS_CLONE_RES_DATA="ORDERS_CLONE_RES_DATA"
export const ORDERS_DELETE_RES_DATA="ORDERS_DELETE_RES_DATA"
export const GET_ORDER_ID_DATA="GET_ORDER_ID_DATA"
export const BULK_SHIP_DATA="BULK_SHIP_DATA"

